- hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - vars/vars.yml
  tasks:
    ## Provision a CA
    - name: Generate the private CA key
      openssl_privatekey:
        force: false
        path: /etc/ssl/private/k8s_ca.pem
        size: 4096
        type: RSA

    - name: Generate the private CA CSR
      openssl_csr:
        common_name: Kubernetes          # CN
        country_name: US                 # C
        force: false
        locality_name: "Salt Lake City"  # L
        organization_name: Kubernetes    # O
        organizational_unit_name: CA     # OU
        path: /etc/ssl/certs/k8s_ca.csr
        privatekey_path: /etc/ssl/private/k8s_ca.pem
        state_or_province_name: UT       # ST

    ## Use selfsigned provider here
    - name: Generate the private CA Cert
      openssl_certificate:
        csr_path: /etc/ssl/certs/k8s_ca.csr
        force: false
        path: /etc/ssl/certs/k8s_ca.crt
        privatekey_path: /etc/ssl/private/k8s_ca.pem
        provider: selfsigned

    ## Provision Admin Client Certs
    - name: Generate the admin client private key
      openssl_privatekey:
        force: false
        path: /etc/ssl/private/k8s_admin_key.pem
        size: 4096
        type: RSA

    - name: Generate the admin client CSR
      openssl_csr:
        country_name: US                                     # C
        force: false
        locality_name: "Salt Lake City"                      # L
        organization_name: "system:masters"                  # O
        organizational_unit_name: "Kubernetes The Hard Way"  # OU
        path: /etc/ssl/certs/k8s_admin.csr
        privatekey_path: /etc/ssl/private/k8s_admin_key.pem
        state_or_province_name: UT                           # ST

    ## Use ownca provider here
    - name: Generate the the admin client cert
      openssl_certificate:
        csr_path: /etc/ssl/certs/k8s_admin.csr
        force: false
        ownca_path: /etc/ssl/certs/k8s_ca.crt
        ownca_privatekey_path: /etc/ssl/private/k8s_ca.pem
        path: /etc/ssl/certs/k8s_admin.crt
        privatekey_path: /etc/ssl/private/k8s_admin_key.pem
        provider: ownca

    ## Provision Kubelet client certs
    - name: Generate the Kubelet client keys
      openssl_privatekey:
        force: false
        path: /etc/ssl/private/k8s_kubelet_{{ item }}_key.pem
        size: 4096
        type: RSA
      loop: "{{ worker_hostnames }}"

    - name: Generate the Kubelet client CSRs
      openssl_csr:
        country_name: US                                     # C
        force: false
        locality_name: "Salt Lake City"                      # L
        organization_name: "system:node:{{ item }}"          # O
        organizational_unit_name: "Kubernetes The Hard Way"  # OU
        path: /etc/ssl/certs/k8s_kubelet_{{ item }}.csr
        privatekey_path: /etc/ssl/private/k8s_kubelet_{{ item }}_key.pem
        state_or_province_name: UT                           # ST
      loop: "{{ worker_hostnames }}"

    - name: Generate the the Kubelet client certs
      openssl_certificate:
        csr_path: /etc/ssl/certs/k8s_kubelet_{{ item }}.csr
        force: false
        ownca_path: /etc/ssl/certs/k8s_ca.crt
        ownca_privatekey_path: /etc/ssl/private/k8s_ca.pem
        path: /etc/ssl/certs/k8s_kubelet_{{ item }}.crt
        privatekey_path: /etc/ssl/private/k8s_kubelet_{{ item }}_key.pem
        provider: ownca
      loop: "{{ worker_hostnames }}"

    ## Provision the Controller Manager client certs
    - name: Generate Controller Manager client keys
      openssl_privatekey:
        force: false
        path: /etc/ssl/private/k8s_controller_manager_key.pem
        size: 4096
        type: RSA

    - name: Generate the Controller Manager client CSRs
      openssl_csr:
        country_name: US                                     # C
        force: false
        locality_name: "Salt Lake City"                      # L
        organization_name: "system:kube-controller-manager"  # O
        organizational_unit_name: "Kubernetes The Hard Way"  # OU
        path: /etc/ssl/certs/k8s_controller_manager.csr
        privatekey_path: /etc/ssl/private/k8s_controller_manager_key.pem
        state_or_province_name: UT                           # ST

    - name: Generate the the Controller Manager client certs
      openssl_certificate:
        csr_path: /etc/ssl/certs/k8s_controller_manager.csr
        force: false
        ownca_path: /etc/ssl/certs/k8s_ca.crt
        ownca_privatekey_path: /etc/ssl/private/k8s_ca.pem
        path: /etc/ssl/certs/k8s_controller_manager.crt
        privatekey_path: /etc/ssl/private/k8s_controller_manager_key.pem
        provider: ownca
