name: "Lint Playbooks"
on:
  pull_request:
    branches:
      - main
jobs:
  lint-playbooks:
    name: lint-ansible-playbooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
  
    - name:  Lint Playbooks
      id: ansible-lint
      uses: ansible/ansible-lint@v6
